### PR TITLE
update category to Generate from Path

### PR DESCRIPTION
**Pull request by Neon22**
Two changes.
1. This change ensures dimension line drawn outside of points. It no longer draws a dimension line in between the two end points.
   - Probably a neater way to do this but I have tested vertical,horizontal, parallel in all four quadrants. See test image.
2. The category "Generate from Path" seems better suited because the dimensions are created from a selected path but do not modify that path. The current category is "Modify Path".

dimensions-test-palette

### CODE REVIEW

**Comment by Neon22** [comment]
Sorry this has same content as the previous pull request but I added category change to "Generate from Path".
Not sure why its not added the committ to the previous pull request.
Very sorry about confusion

**Comment by Neon22** [comment]
The first three commits are empty - sorry should have squashed those. Just me trying to get my git repo in order...

**Comment by Rutzmoser** [comment]
Amazing work! Sorry, that I didn't come earlier to merge this feature.

**Comment by Neon22** [comment]
Cheers, thanks for making it in the first place. I jus tstarted an arc based one - so wil lsubmit a new PR soon. You can place it up on the new inkscape plugin page. People woudl really appreciate it.

Here are the instructions:

```
How to make your extension visible on the inkscape.org website.
Three main steps but some prep work to do beforehand.

Upload:
Step 1. Goto inkscape.org and create an account if you don't already have one.
        - https://inkscape.org
Step 2. At top of your login page you will see a link to "Upload Art or Resource"
        - This link also appears on your home page in a side panel as "New Upload"
Step 3. Clicking on either these will take you to an upload page where you can
        upload a zip file, thumbnail and text description and some tags.
    Your description should say on which menu the extension is to be found.

Preparation:
These Items need to be prepared for upload:
1. Zip file of your inx and py files as well as any subfolders or other files you might need.
   Optionally include a license and install file if needed.
   The current install direction is at the top of this page
    - https://inkscape.org/en/download/addons/
    and guarantees each user can get the files into the right place.
   But your extension might be a replacement for a distributed one, or special in some
    other way, in which case adding specific install information is advisable.
   Please name these files "yourextension_install.txt" and "yourextension.license"
    then they will not collide with other extensions files in the directory.
    (This is a traditional problem with "README.md" and INSTALL from git repos.)

2. A thumbnail. This should be a png or jpg and 190x190 in size. 
   This will appear on the extensions page here:
    - https://inkscape.org/en/download/addons/

3. Use tags to indicate which build your extension works in.
    "0.91" for current build. 
    "0.48" if it works in previous build also.
    "Windows", Linux, Mac if know it work son those.
    Soon we hope to be able to add any other tags you think relevant.

Note:
- Remember to license your code using an OS license. Currently the upload will only accept:
  - GPLv2/v3, LGPLv2/v3, AGPLv3, MIT.
  Regrettably if your license is not one of these, you won't be able to upload it.
  (Feedback to dev forums).

- When uploading, the zip and thumbnail cannot be uploaded at the same time. 
   This may change in the future.
- For now. Upload the zip file first along with all fields except the thumbnail.
   Then edit the resulting page and upload the thumbnail.
   On this second visit you may think there is no zip file but it remains attached
    but not shown in the form.
   Proceed to upload the thumbnail and review your submission on the addons page:
    - https://inkscape.org/en/download/addons/

```

**Pull request merged**
